import { StyleSheet } from 'react-native';
import { stitchColors } from '../../theme/stitchColors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: stitchColors.background,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: '100%',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 40,
    justifyContent: 'center',
  },
  gridLineH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(229, 226, 225, 0.03)',
  },
  gridLineV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(229, 226, 225, 0.03)',
  },
  gradientWash: {
    ...StyleSheet.absoluteFillObject,
  },
  glowTop: {
    position: 'absolute',
    top: '-10%',
    right: '-10%',
    width: '55%',
    height: '38%',
    borderRadius: 999,
    backgroundColor: `${stitchColors.secondary}1a`,
  },
  glowBottom: {
    position: 'absolute',
    bottom: '-5%',
    left: '-5%',
    width: '42%',
    height: '32%',
    borderRadius: 999,
    backgroundColor: `${stitchColors.primaryContainer}1a`,
  },
  mainColumn: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    gap: 28,
  },
  heroBlock: {
    gap: 20,
    marginBottom: 8,
  },
  eyebrow: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: stitchColors.surfaceContainerHighest,
  },
  eyebrowText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 3.2,
    color: stitchColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: -2,
    color: stitchColors.onSurface,
    lineHeight: 54,
  },
  subtitle: {
    fontSize: 17,
    lineHeight: 26,
    color: stitchColors.onSurfaceVariant,
    opacity: 0.85,
    maxWidth: 340,
  },
  card: {
    backgroundColor: `${stitchColors.surfaceContainerHigh}99`,
    borderLeftWidth: 1,
    borderLeftColor: stitchColors.white05,
    paddingHorizontal: 28,
    paddingTop: 36,
    paddingBottom: 28,
    overflow: 'hidden',
  },
  lockDeco: {
    position: 'absolute',
    top: 12,
    right: 12,
    opacity: 0.1,
  },
  lockDecoText: {
    fontSize: 56,
    color: stitchColors.onSurface,
  },
  form: {
    gap: 28,
  },
  field: {
    gap: 8,
  },
  label: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    color: stitchColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  labelFocused: {
    color: stitchColors.primaryContainer,
  },
  input: {
    fontSize: 17,
    color: stitchColors.onSurface,
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: `${stitchColors.outlineVariant}4d`,
  },
  inputFocused: {
    borderBottomColor: stitchColors.primaryContainer,
  },
  ctaOuter: {
    marginTop: 4,
    borderRadius: 2,
    overflow: 'hidden',
  },
  cta: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
  },
  ctaText: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: stitchColors.onPrimary,
  },
  ctaArrow: {
    fontSize: 22,
    color: stitchColors.onPrimary,
  },
  linksRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
  },
  link: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 2,
    color: stitchColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  metaRow: {
    marginTop: 36,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: stitchColors.white10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    opacity: 0.35,
  },
  metaCol: {
    gap: 4,
  },
  metaColEnd: {
    alignItems: 'flex-end',
  },
  metaKicker: {
    fontSize: 8,
    letterSpacing: 0.5,
    color: stitchColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  metaValue: {
    fontSize: 10,
    fontWeight: '800',
    color: stitchColors.onSurface,
  },
  footerNote: {
    marginTop: 28,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    opacity: 0.35,
  },
  footerNoteText: {
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 3,
    color: stitchColors.onSurfaceVariant,
    textTransform: 'uppercase',
  },
  footerRule: {
    width: 72,
    height: 1,
    backgroundColor: stitchColors.onSurfaceVariant,
  },
});
